// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TonyDataAccessLayer;

#nullable disable

namespace TonyDataAccessLayer.Migrations
{
    [DbContext(typeof(TonyDbContext))]
    partial class TonyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TonyDataAccessLayer.Models.SubmissionModel", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("MemoryTakenInKiloBytes")
                        .HasColumnType("int");

                    b.Property<string>("Output")
                        .HasColumnType("longtext");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TimeTakenInMilliSeconds")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
