apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: online-judge
type: Opaque
stringData:
  default_connection: "server=some-mysql;port=3306;user=root;password=mysqldatabase123;database=OJ"
